### ISSUE TITLE
change orientaion, the toast will wrong

### ISSUE THREAD

**Issue by EvenYu** [Brite-Apps/WToast#4]
mainsrcreen is portriat, then the show toast's viewcontroller ,which is landscape;now the toast will show wrong.

**Comment by Narmo** [comment]
@EvenYu Do you use last version of WToast? I cannot reproduce bug you mentioned.

**Comment by shivideal** [comment]
can we chagne the placement of toast , can we show it in upper side of screen

**Comment by Narmo** [comment]
@shivideal Great idea, thank you. I've implemented "gravity" param, please look at the latest version.
